%YAML:1.0

#### Settings for my dataset, revise for specific dataset accordingly. #####

# Tracking frequency
fps: 5

# How many images, start and max
img_start_idx: 30
img_count: 2000

# Accepted feature depth bounds [mm]
upper_depth: 3600.0
lower_depth: 2300.0

# For lose detection
max_linear_speed: 2000     # 2000 mm/s
max_angular_speed: 200    # 200 degree/s

# For feature detection
scale_factor: 1.2   # > 1
feature_sigma: 0.5  # useless for now
max_level: 1        # 1 level for upward camera
max_feature_num: 500


# Optimization
## Robust kernel for 2d MapPoint constraint
th_huber2: 5.991
## How many loops in optimizer iteration
local_iter: 10
global_iter: 12
## 1 for print debug info, 0 for not
local_print: 1
global_print: 1

# For odometry uncertainty
odo_x_uncertain: 0.01
odo_y_uncertain: 0.01
odo_theta_uncertain: 0.01

# For odometry noise (in a moment) (unit: mm, rad)
odo_x_steady_noise: 1.0
odo_y_steady_noise: 1.0
odo_theta_steady_noise: 0.005

# For plane motion constraint
plane_motion_xrot_info: 1e6
plane_motion_yrot_info: 1e6
plane_motion_z_info: 1

# For local graph (unit: m)
max_local_frame_num: 10         # 10
local_frame_search_level: 2     # 1
local_frame_search_radius: 0.3  # 0.3

# For global map loopclose
gm_vcl_num_min_match_mp: 12
gm_vcl_num_min_match_kp: 24
gm_vcl_ratio_min_match_kp: 0.05
gm_dcl_min_kfid_offset: 25
gm_dcl_min_score_best: 0.05

# For map storage
## 1 if use previously saved map, 0 if not
use_prev_map: 0
## 1 if save map when exit, o if not
save_new_map: 1
## 1 if disable SLAM and do localization only (use_prev_map must be 1), 0 if do SLAM
localization_only: 0
## map file config
map_file_store_path: "/home/vance/output/rk_se2lam/map-1/"
read_map_file_name: "se2-rk-1.map"
write_map_file_name: "se2-rk-1.map"
write_traj_file_name: "se2-rk-1.traj"

# For visulization
need_visulization: 1    # if 0, images will not be saved.
mappub_scale_ratio: 300


# For debug
## 1 for verbose, 0 for non-verbose
local_verbose: 0
global_verbose: 0

save_match_image: 0
match_image_store_path: "/home/vance/output/rk_se2lam/match-1/"
